name: Execute Notebook

on:
  workflow_dispatch: # Allows the workflow to be triggered manually or via API

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install jupyter nbconvert pandas numpy matplotlib datetime openpyxl

    - name: Execute notebook
      run: |
        jupyter nbconvert --execute --to notebook --output output.ipynb Graficos_Relatorio_Performance.ipynb || exit 1

    - name: Upload Notebook (Optional)
      uses: actions/upload-artifact@v3
      with:
        name: executed-notebook
        path: output.ipynb

    - name: Commit graphs to repository
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add graficos_relatorio/
        git commit -m "Add generated graphs"
        git push
